### ISSUE TITLE
Upgrade to Prawn 1.3 and drop Ruby 1.8.7 support

### ISSUE THREAD

**Issue by hidakatsuya** [thinreports/thinreports-generator#11]
Changelogs for Prawn:

  * 0.12.0-0.15.0: https://github.com/prawnpdf/prawn/wiki/CHANGELOG
  * 1.0-1.3: http://prawnpdf.org/api-docs/2.0/file.CHANGELOG.html

**NOTE:**
In thinreports 1.0, we have a plan to upgrade to Prawn 2.x and drop Ruby 1.9.3 support #12.

**Tasks:**

- [ ] Upgrade to Prawn 1.3
- [x] Drop Ruby 1.8.7 support
- [ ] Remove unnecessary extentions, patches and guards

**Comment by eitoball** [comment]
:+1:
